---
language: node_js
node_js:
  - "6"

sudo: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache

before_install:
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - COVERAGE=true ember exam --random

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash scripts/deploy.sh
